/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { useState, useEffect } from 'react';
import { DatabaseService } from '../services/database';
import { Customer, Product, Order } from '../types';
import { Users, Package, ShoppingBag, DollarSign, ArrowRight, CheckCircle, Clock } from 'lucide-react';

interface DashboardViewProps {
  onNavigate: (tab: string) => void;
}

export default function DashboardView({ onNavigate }: DashboardViewProps) {
  const [customers, setCustomers] = useState<Customer[]>([]);
  const [products, setProducts] = useState<Product[]>([]);
  const [orders, setOrders] = useState<Order[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchDashboardData() {
      try {
        setLoading(true);
        const [cList, pList, oList] = await Promise.all([
          DatabaseService.customers.list(),
          DatabaseService.products.list(),
          DatabaseService.orders.list()
        ]);
        setCustomers(cList);
        setProducts(pList);
        setOrders(oList);
      } catch (err) {
        console.error('Failed to load dashboard data:', err);
      } finally {
        setLoading(false);
      }
    }

    fetchDashboardData();
  }, []);

  const totalCustomers = customers.length;
  const totalProducts = products.length;
  const totalOrders = orders.length;

  // Revenue is only generated by CONFIRMED orders
  const confirmedOrders = orders.filter(o => o.status === 'Confirmed');
  const totalRevenue = confirmedOrders.reduce((sum, o) => sum + o.total_price, 0);

  // Status distribution
  const draftCount = orders.filter(o => o.status === 'Draft').length;
  const confirmedCount = confirmedOrders.length;

  // Let's create dummy historical data points based on confirmed orders or fixed Odoo-like timeline
  const chartData = [
    { label: 'Jan', value: 450 },
    { label: 'Feb', value: 890 },
    { label: 'Mar', value: 1250 },
    { label: 'Apr', value: 1100 },
    { label: 'May', value: totalRevenue > 0 ? totalRevenue : 2390 }
  ];

  const maxChartValue = Math.max(...chartData.map(d => d.value), 100);

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center h-96">
        <div className="animate-spin rounded-full h-10 w-10 border-4 border-purple-600 border-t-transparent mb-4"></div>
        <p className="text-slate-500 text-sm font-medium">Aggregating Odoo dashboard metrics...</p>
      </div>
    );
  }

  return (
    <div className="space-y-8 animate-fade-in">
      
      {/* Header Info */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-800 tracking-tight">Sales Dashboard</h1>
          <p className="text-slate-500 text-sm mt-0.5">Monitor key sales performance indicators, customer engagement trends, and order lifecycle distribution in real-time.</p>
        </div>
      </div>

      {/* KPI Cards Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
        
        {/* Total Customers */}
        <div 
          onClick={() => onNavigate('customers')}
          className="bg-white p-6 rounded-2xl border border-slate-200 hover:border-purple-300 shadow-sm hover:shadow-md transition-all cursor-pointer group"
        >
          <div className="flex items-center justify-between mb-4">
            <span className="text-slate-400 font-medium text-xs uppercase tracking-wider">Total Customers</span>
            <div className="p-2.5 bg-blue-50 text-blue-600 rounded-xl group-hover:scale-110 transition-transform">
              <Users className="w-5 h-5" />
            </div>
          </div>
          <div className="flex items-baseline gap-2">
            <span id="kpi-customers-count" className="text-3xl font-bold text-slate-800 tracking-tight">{totalCustomers}</span>
            <span className="text-xs text-blue-600 font-medium">B2B Contacts</span>
          </div>
          <div className="flex items-center gap-1 text-slate-400 text-xs mt-3 group-hover:text-[#714B67] transition-all">
            <span>Manage directory</span>
            <ArrowRight className="w-3.5 h-3.5" />
          </div>
        </div>

        {/* Total Products */}
        <div 
          onClick={() => onNavigate('products')}
          className="bg-white p-6 rounded-2xl border border-slate-200 hover:border-purple-300 shadow-sm hover:shadow-md transition-all cursor-pointer group"
        >
          <div className="flex items-center justify-between mb-4">
            <span className="text-slate-400 font-medium text-xs uppercase tracking-wider">Product Catalog</span>
            <div className="p-2.5 bg-amber-50 text-amber-600 rounded-xl group-hover:scale-110 transition-transform">
              <Package className="w-5 h-5" />
            </div>
          </div>
          <div className="flex items-baseline gap-2">
            <span id="kpi-products-count" className="text-3xl font-bold text-slate-800 tracking-tight">{totalProducts}</span>
            <span className="text-xs text-amber-600 font-medium">Items</span>
          </div>
          <div className="flex items-center gap-1 text-slate-400 text-xs mt-3 group-hover:text-[#714B67] transition-all">
            <span>View inventory</span>
            <ArrowRight className="w-3.5 h-3.5" />
          </div>
        </div>

        {/* Total Orders */}
        <div 
          onClick={() => onNavigate('orders')}
          className="bg-white p-6 rounded-2xl border border-slate-200 hover:border-purple-300 shadow-sm hover:shadow-md transition-all cursor-pointer group"
        >
          <div className="flex items-center justify-between mb-4">
            <span className="text-slate-400 font-medium text-xs uppercase tracking-wider">Sales Orders</span>
            <div className="p-2.5 bg-purple-50 text-[#714B67] rounded-xl group-hover:scale-110 transition-transform">
              <ShoppingBag className="w-5 h-5" />
            </div>
          </div>
          <div className="flex items-baseline gap-2">
            <span id="kpi-orders-count" className="text-3xl font-bold text-slate-800 tracking-tight">{totalOrders}</span>
            <span className="text-xs text-[#714B67] font-medium">
              {draftCount} draft, {confirmedCount} confirmed
            </span>
          </div>
          <div className="flex items-center gap-1 text-slate-400 text-xs mt-3 group-hover:text-[#714B67] transition-all">
            <span>Process orders</span>
            <ArrowRight className="w-3.5 h-3.5" />
          </div>
        </div>

        {/* Confirmed Revenue */}
        <div 
          onClick={() => onNavigate('reports')}
          className="bg-[#714B67] text-white p-6 rounded-2xl shadow-md hover:shadow-lg transition-all cursor-pointer group"
        >
          <div className="flex items-center justify-between mb-4">
            <span className="text-purple-200 font-medium text-xs uppercase tracking-wider">Revenue (Confirmed)</span>
            <div className="p-2.5 bg-white/10 text-amber-400 rounded-xl group-hover:scale-110 transition-transform">
              <DollarSign className="w-5 h-5" />
            </div>
          </div>
          <div className="flex items-baseline gap-2">
            <span id="kpi-revenue" className="text-3xl font-bold tracking-tight">
              ${totalRevenue.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
            </span>
          </div>
          <div className="flex items-center gap-1 text-purple-200 text-xs mt-3 group-hover:text-amber-300 transition-all">
            <span>Analyze sales details</span>
            <ArrowRight className="w-3.5 h-3.5" />
          </div>
        </div>

      </div>

      {/* Main Charts Row */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Custom Hand-crafted Revenue Chart */}
        <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm lg:col-span-2">
          <div className="flex justify-between items-center mb-6">
            <div>
              <h2 className="text-base font-bold text-slate-800">Revenue Growth Trend</h2>
              <p className="text-xs text-slate-400">Monthly confirmed invoice volumes (USD)</p>
            </div>
            <span className="text-xs bg-slate-100 border border-slate-200 text-slate-600 px-2 py-1 rounded">2026 Sandbox</span>
          </div>

          {/* SVG Vector Chart */}
          <div className="h-64 flex flex-col justify-between">
            <div className="relative h-48 flex items-end justify-between px-4 pb-2 border-b border-dashed border-slate-100">
              
              {/* Background horizontal lines grid */}
              <div className="absolute inset-0 flex flex-col justify-between pointer-events-none z-0">
                <div className="border-t border-slate-100 w-full h-0"></div>
                <div className="border-t border-slate-100 w-full h-0"></div>
                <div className="border-t border-slate-100 w-full h-0"></div>
                <div className="border-t border-slate-100 w-full h-0"></div>
              </div>

              {chartData.map((data, idx) => {
                const heightPercent = maxChartValue > 0 ? (data.value / maxChartValue) * 100 : 0;
                return (
                  <div key={idx} className="flex flex-col items-center flex-1 z-10 group relative max-w-[60px] mx-auto">
                    {/* Tooltip on hover */}
                    <div className="absolute -top-12 bg-slate-800 text-white rounded px-2 py-1 text-[10px] font-semibold opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none shadow-md">
                      ${data.value.toFixed(2)}
                    </div>
                    {/* Visual bar */}
                    <div 
                      className={`w-full rounded-t-lg transition-all duration-1000 origin-bottom group-hover:opacity-80 cursor-pointer ${
                        idx === chartData.length - 1 ? 'bg-[#714B67]' : 'bg-slate-300'
                      }`}
                      style={{ height: `${Math.max(heightPercent, 8)}%` }}
                    ></div>
                    {/* Bar Label */}
                    <span className="text-[11px] font-medium text-slate-400 mt-2">{data.label}</span>
                  </div>
                );
              })}
            </div>
            <div className="text-[10px] text-slate-400 flex justify-between pr-4 pl-4 pt-1">
              <span>$0.00</span>
              <span>Mid Limit</span>
              <span>Max: ${maxChartValue.toFixed(2)}</span>
            </div>
          </div>
        </div>

        {/* Order Status Breakdown */}
        <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm flex flex-col justify-between">
          <div>
            <h2 className="text-base font-bold text-slate-800 mb-1">Workflow Breakdown</h2>
            <p className="text-xs text-slate-400 mb-6">Distribution of orders in the sales funnel.</p>

            <div className="space-y-4">
              {/* Confirmed Orders list bar */}
              <div>
                <div className="flex justify-between items-center text-xs font-semibold text-slate-600 mb-1">
                  <span className="flex items-center gap-1.5">
                    <CheckCircle className="w-4 h-4 text-emerald-500" />
                    Confirmed Sales
                  </span>
                  <span>{confirmedCount} ({totalOrders > 0 ? Math.round((confirmedCount / totalOrders) * 100) : 0}%)</span>
                </div>
                <div className="w-full h-2.5 bg-slate-100 rounded-full overflow-hidden">
                  <div 
                    className="h-full bg-emerald-500 rounded-full transition-all duration-1000"
                    style={{ width: `${totalOrders > 0 ? (confirmedCount / totalOrders) * 100 : 0}%` }}
                  ></div>
                </div>
              </div>

              {/* Draft Orders list bar */}
              <div>
                <div className="flex justify-between items-center text-xs font-semibold text-slate-600 mb-1">
                  <span className="flex items-center gap-1.5">
                    <Clock className="w-4 h-4 text-amber-500" />
                    Draft Quotations
                  </span>
                  <span>{draftCount} ({totalOrders > 0 ? Math.round((draftCount / totalOrders) * 100) : 0}%)</span>
                </div>
                <div className="w-full h-2.5 bg-slate-100 rounded-full overflow-hidden">
                  <div 
                    className="h-full bg-amber-400 rounded-full transition-all duration-1000"
                    style={{ width: `${totalOrders > 0 ? (draftCount / totalOrders) * 100 : 0}%` }}
                  ></div>
                </div>
              </div>
            </div>
          </div>

          <div className="bg-slate-50 p-4 rounded-xl border border-slate-100 mt-6">
            <h3 className="text-xs font-bold text-[#714B67] uppercase tracking-wider mb-1">Odoo Tip</h3>
            <p className="text-xs text-slate-500 leading-relaxed leading-sans">
              "Draft" status denotes quotation negotiations. Click "Confirm" on any draft order state to update official stocks and aggregate official invoice revenue!
            </p>
          </div>
        </div>

      </div>

      {/* Latest Orders Table list */}
      <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
        <div className="px-6 py-4 border-b border-slate-100 flex justify-between items-center">
          <div>
            <h2 className="text-base font-bold text-slate-800">Recent Quotations & Orders</h2>
            <p className="text-xs text-slate-400">Latest pipeline transactions across all customers.</p>
          </div>
          <button 
            onClick={() => onNavigate('orders')}
            className="text-xs font-semibold text-[#714B67] hover:text-[#5d3d54] hover:underline flex items-center gap-1 active:scale-95 cursor-pointer"
          >
            <span>View all orders</span>
            <ArrowRight className="w-3.5 h-3.5" />
          </button>
        </div>

        {orders.length === 0 ? (
          <div className="text-center py-10 text-slate-400 text-sm">
            No sales orders generated yet. Keep the pipeline moving!
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse text-sm">
              <thead className="bg-slate-50 border-b border-slate-100 text-xs font-semibold text-slate-400 uppercase tracking-wider">
                <tr>
                  <th className="py-3.5 px-6">Order Ref</th>
                  <th className="py-3.5 px-6">Customer</th>
                  <th className="py-3.5 px-6">Created On</th>
                  <th className="py-3.5 px-6 text-right">Total Amount</th>
                  <th className="py-3.5 px-6 text-center">Status</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 text-slate-700">
                {orders.slice(0, 5).map((o) => (
                  <tr key={o.id} className="hover:bg-slate-50/50 transition-colors">
                    <td className="py-3.5 px-6 font-semibold text-slate-900">{o.id}</td>
                    <td className="py-3.5 px-6">{o.customer_name || 'Generic Customer'}</td>
                    <td className="py-3.5 px-6 text-slate-500">
                      {new Date(o.created_at).toLocaleDateString(undefined, { 
                        year: 'numeric', 
                        month: 'short', 
                        day: 'numeric' 
                      })}
                    </td>
                    <td className="py-3.5 px-6 text-right font-bold text-slate-900">
                      ${o.total_price.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                    </td>
                    <td className="py-3.5 px-6 text-center">
                      <span className={`inline-flex items-center px-2.5 py-1 rounded-full text-xs font-semibold ${
                        o.status === 'Confirmed' 
                          ? 'bg-emerald-50 text-emerald-700' 
                          : 'bg-amber-50 text-amber-700 border border-amber-200'
                      }`}>
                        {o.status}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

    </div>
  );
}
